# Generated by Django 4.1.6 on 2023-02-14 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='answer',
            field=models.TextField(blank=True, null=True),
        ),
    ]
